# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('isDelete', models.BooleanField(default=False, verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('name', models.CharField(max_length=20, verbose_name='\u5546\u54c1SPU\u540d\u79f0')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='\u5546\u54c1\u8be6\u60c5')),
            ],
            options={
                'db_table': 'df_goods',
                'verbose_name': '\u5546\u54c1SPU',
                'verbose_name_plural': '\u5546\u54c1SPU',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('isDelete', models.BooleanField(default=False, verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('name', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('desc', models.CharField(max_length=256, verbose_name='\u5546\u54c1\u7b80\u4ecb')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('unite', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u5355\u4f4d')),
                ('image', models.ImageField(upload_to='goods', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('stock', models.IntegerField(default=1, verbose_name='\u5546\u54c1\u5e93\u5b58')),
                ('sales', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u9500\u91cf')),
                ('status', models.SmallIntegerField(choices=[(0, '\u4e0b\u7ebf'), (1, '\u4e0a\u7ebf')], default=1, verbose_name='\u5546\u54c1\u72b6\u6001')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.Goods', verbose_name='\u5546\u54c1SPU')),
            ],
            options={
                'db_table': 'df_goods_sku',
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('isDelete', models.BooleanField(default=False, verbose_name=b'\xe5\x88\xa0\xe9\x99\xa4\xe6\xa0\x87\xe8\xae\xb0')),
                ('name', models.CharField(max_length=20, verbose_name='\u79cd\u7c7b\u540d\u79f0')),
                ('logo', models.CharField(max_length=20, verbose_name='\u6807\u8bc6')),
                ('image', models.ImageField(upload_to='type', verbose_name='\u5546\u54c1\u7c7b\u578b\u56fe\u7247')),
            ],
            options={
                'db_table': 'df_goods_type',
                'verbose_name': '\u5546\u54c1\u79cd\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u79cd\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsType', verbose_name='\u5546\u54c1\u79cd\u7c7b'),
        ),
    ]
